apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
# https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#system-level-configuration
# ignore the caBundle field of a mutating webhook e.g. metallb
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'